### ISSUE TITLE
Alteração na parte inferior da plataforma (Disclaimer e terms and Conditions)

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#48]
Wilson, boa noite!
Precisamos fazer alteração na parte inferior da plataforma:
1) Substituir o texto dos 5 bullets points pelo texto que esta no primeiro anexo (ppt.).
2) Criar um hyperlink (logo abaixo do novo texto) e uma página que abrirá com o texto **Terms and Conditions for use of the Site BP** (.docx).  Fiz um exemlo no arquivo em pptx.

[Disclaimer_TermsAndConditions.pptx](https://github.com/bireme/ods3-best-practices/files/8338199/Disclaimer_TermsAndConditions.pptx)
[Terms_and_Conditions_for_use_of_the_Site_BP_.docx](https://github.com/bireme/ods3-best-practices/files/8338201/Terms_and_Conditions_for_use_of_the_Site_BP_.docx)

Obrigada!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados conforme solicitado. Favor validar.
