### ISSUE TITLE
Inclusão de novo campo no formulário e alteração da ordem dos itens do select box

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#51]
Wilson, boa tarde!
Seguem algumas alterações no formulário do Portal Boas Práticas:

1) Em Type/Description - Main Topics/Themes: quando a pessoa selecionar "Other", incluir um campo para a pessoa poder escrever (o nome do campo será: Other main topic/theme (please specify) 
       1.1) Deixar o campo de escrever apenas para quando a opção "Other" for selecionada.

2) Em Type/Description - Main Topics/Themes: colocar a opção "Other" como última opção na select box.

3) Em Type/Description - Interventions: colocar a opção "Other" como última opção na select box.

Obrigada!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados. Favor validar.
