### ISSUE TITLE
Possibilitar selecionar mais de um item nos select boxes

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#53]
Wilson, boa tarde!

Seria possível permtir a seleção de mais de um item nos seguintes selec boxes?

1) Country/Territory receiving/providing the cooperation
2) Subregion
3) Entity (PAHO)
4) Counterparts and Partnerships

Obrigada!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados. Favor validar.
