### ISSUE TITLE
E-mail do Portal Boas Práticas

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#55]
Wilson, Boa tarde!

Já temos acesso ao e-mail do Portal: bp@paho.org
Você poderia, por gentileza, encaminhar novamente o link para a validação?!
Assim, podemos fazer os testes (se os e-mail do Portal chegam na caixa do bp@paho.org).

Obrigada!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe uma nova mensagem de confirmação foi enviada para o email bp@paho.org.

**Comment by wilsonmoura** [comment]
@isabellaabe uma nova mensagem de confirmação foi enviada para o email bp@paho.org. Favor confirmar o recebimento dessa mensagem.
