### ISSUE TITLE
Novos campos no formulário

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#56]
Prezado Wilson, bom dia!

Solicitamos, por gentileza, a inclusão de novos campos no formulário: 

1. Em Basic Information, e logo após “This Best Practice is related to:”, incluir a seguinte pergunta e as opções (select box):

Modality of Cooperation:
      North-North
      North-South
      South-South
      Triangular Cooperation

2. Em Effectiveness/Efficiency/Adaptability/Replicability: 
        2.1. Incluir a pergunta e a caixa de texto:
        Please, describe the sustainability aspect of the project/initiative being described in this Best Practice.
        
        2.2. Incluir a palavra Sustainability na aba:
        Effectiveness/Efficiency/Adaptability/Replicability/Sustainability

3. Em Multimedia/Conclusão: incluir campo de inclusão de palavras-chaves. Conectar com o DeCS.

Obrigada!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados conforme solicitado.
