### ISSUE TITLE
Ajuste - formulário 

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#57]
Wilson, boa tarde!

Dois ajustes no formulário:

Nas questões em vermelho, que são as obrigatórias, colocar um asterísco ao final de cada pergunta. E também, ao final de cada página inserir "*Mandatory".

Em Keywords, adicionar o “?” azul, conforme imagem em anexo e escrever: Please choose at least three descriptors.
![Formulario_ajustes](https://user-images.githubusercontent.com/102256433/180880998-e4d7c03a-d013-49c1-90b7-8d11ec0bc0dc.png)

Obrigada!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe com relação aos campos obrigatórios, nossa sugestão é remover a cor vermelha do nome dos campos, pois normalmente a cor vermelha representa erro na informação daquele respectivo campo. Segue imagem do exemplo sugerido:

![screenshot-ods3 local bvsalud org-2022 07 26-21_34_34](https://user-images.githubusercontent.com/3779520/181135737-e1ee55c6-eb56-4907-8566-2d51d82d82fd.png)

**Comment by isabellaabe** [comment]
OI Wilson, boa tarde.
De acordo com a sua proposta. A única alterção seria colocar a informação "*Mandatory Fiel" no inicio do formulário (por exemplo, depois de Basci Information) e em todos os passos.
Obrigada!
Isabella
