### ISSUE TITLE
Inserir texto na parte inferior do formulário de novo usuário

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#58]
Oi Wilson, boa tarde!!

Por favor, inserir este texto abaixo no formulário de criação de novo usuário.

If you do not see the email in your inbox, please check your junk mail folder or spam folder. If you do not receive any emails, then write to [bp@paho.](mailto:bp@paho.org)[org](mailto:bp@paho.org). We will do our best to answer your request as soon as possible.

![Formularionovousuario_ajuste](https://user-images.githubusercontent.com/102256433/182441488-64a54af4-788b-4e43-966f-06bcbfea72c8.png)

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados no ambiente de testes. Pendente tradução para o espanhol. Favor validar.

**Comment by isabellaabe** [comment]
Oi WIlson, boa tarde!
Precis atualizar este texto. Você me ajuda? Segue o novo texto:

If you do not see the confirmation email in your inbox, please check your junk mail folder or spam folder. If you do not receive any email, then write to bp@paho.org. The Best Practices Portal team will do their best to answer your request as soon as possible.

Obrigada!!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados.
