### ISSUE TITLE
Alteração: Revision por Review

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#61]
Oi Wilson, boa tarde!!
Tudo bom?

Precisamos fazer uma alteração no formulário (ver imagem em anexo também).

- Revision por Review
![revision_review](https://user-images.githubusercontent.com/102256433/195398556-587abd23-0097-46fd-a2f2-ba9c88b27556.png)

Obrigada!!

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados conforme solicitado.
