### ISSUE TITLE
Modificação em "Comments for PAHO"

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#62]
Wilson, bom dia! Tudo bom?

Precisamos substituir uma pergunta:

EM: Any comment for the Secretariat of the Pan American Health Organization?
PARA: Any comment to the Secretariat of PAHO's Best Practice Portal?

Obrigada!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados no ambiente de testes. Favor validar.
