### ISSUE TITLE
Alterações no formulário (urgente)

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#63]
Oi Wilson, boa noite!!

Seguem em anexo algumas alterações no formulário que precisamos fazer.

Obrigada!
Isabella
[alteracoes_formulario_BP.pdf](https://github.com/bireme/ods3-best-practices/files/10007310/alteracoes_formulario_BP.pdf)

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados no ambiente de testes. Favor validar.

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados no ambiente de testes. Favor validar e realizar as devidas traduções.
