### ISSUE TITLE
Alterar campo "assunto" das mensagens enviadas pelo sistema

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#64]
Oi Wilson!
Você poderia nos ajudar a trocar o texto que vai no campo "assunto", das mensagens enviadas pelo sistema?
Ainda aparecem nos assustos das mensagens o projeto Proethos, como por exemplo "[BP] New user on Proethos2 platform"

Obrigada!

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados no ambiente de testes. Favor validar e realizar as devidas traduções.

**Comment by AugustoBaron** [comment]
Hola Wilson,

Hemos revisado los correos, y se han generado de manera correcta con sus nuevos títulos. Muchas gracias. Lo único, en vez de decir "Best Practices Platform" podría decir "Best Practices Portal"?

Con ese último cambio si ya podríamos mandarlo a la versión live. Y de ahí nosotros hacemos las traducciones.

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos más algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura,

He revisado los nuevos sujetos de los correos, estos se envían apropiadamente como "[BP] (...) Best Practices Portal".  Agregaremos las traducciones lo más pronto posible.

¡Muchas gracias!
