### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#65]
Hola Wilson,

Conforme a lo discutido, enviamos este issue como la primera prioridad de ajustes al Portal.

Esto se confirma de los bugs que creemos hemos identificado dentro del portal encontrándose:

- El campo de conflicto de interés que se registra automáticamente como 'no'
- Las respuestas de algunos de los campos de 'breakdown menu' no son registradas en el PDF
- Los hyperlinks del campo de sources no están siendo registrados en el PDF
- El token %protocol_code% no está funcionando en algunos correos.

Por favor encuentra descripciones más detalladas de los problemas en el documento adjunto.
[P1 - Bugs.docx](https://github.com/bireme/ods3-best-practices/files/10760571/P1.-.Bugs.docx)

Estamos a la orden para aclarar cualquier duda.

Atentamente,
Augusto/Isabella/Jessica

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Todos los campos en el PDF se están generando de manera correcta en su primer versión y subsecuentes  según mi pruebas.
Los correo que recibí también generaron correctamente el token %protocol_code%.

Se mira listo para la versión live.
Muchas gracias!
