### ISSUE TITLE
Cambios a los roles y lenguaje del sistema

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#67]
Estimado Wilson,

Continuando con la lista de prioridades, en tercer lugar hemos establecido la incorporación de:
- Ocultar la opción para cambiar el lenguaje a francés en la página.
- Retirar de uso el rol "Member ad-hoc" del sistema
- Cambiar el nombre de los siguientes roles de la siguiente manera:

- [ ] Renombrar el rol "Investigator" a "Submitter"
- [ ] Renombrar el rol "Secretary" a "Secretariat"
- [ ] Renombrar el rol "Member of Committee" a "Reviewer"

- El rol Administrator queda igual. 

Por favor encuentra todos los detalles en el documento adjunto: [P3 - Roles y Lenguaje.docx](https://github.com/bireme/ods3-best-practices/files/10760696/P3.-.Roles.y.Lenguaje.docx)

Estamos a la orden para cualquier duda o aclaración que necesites.

Atentamente,
Augusto/Isabella/Jessica

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by AugustoBaron** [comment]
Hola @wilsonmoura,

Acabo de revisar y concuerdo que los nombre de los roles han sido satisfactoriamente cambiados y según mis ensayos - conservan las mismas funciones.

El lenguage de francés lo constato como correctamente escondido.

El rol ad hoc se constata como apropiadamente oculto (o eliminado).

Constaté también que los botones de selección de los reviewers ya fue cambiado también para solo un botón de nombre "Select Members of the Committee" - lo he probado también y conserva las funcionalidades esperadas para asignar las cuentas con rol "Reviewer". 

Estos cambios se constatan listos para el live version.

¡Muchas gracias!
