### ISSUE TITLE
Reemplazo de textos

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#68]
Estimado Wilson,

Continuando con la lista de prioridades, en cuarto lugar hemos establecido ciertos cambios de texto.

En el Submission form (https://admin.bestpractices.bvsalud.org/submission/new/first), detallamos los siguientes cambios:

- Step 6: “Sources/Comments”
Cambiar el texto del primer text box de "Please provide sources and documents of the initiative/project generated/associated to this Best Practice (hyperlinks only):" a “Please provide hyperlinks to sources/documents associated with the Best Practice.”
- Step 6: “Sources/Comments”
Cambiar el texto del título “Comments for PAHO” a “Comments for the Pan American Health Organization”.
- Step 6: “Sources/Comments”
Cambiar el texto del último text box de “Any comment to the Secretariat of PAHO's Best Practice Portal?” a “Please provide comments for the PAHO’s Best Practices Secretariat (Optional)”.
- Step 4 “Relevance/Recognition/Engagement”
Cambiar el título “Engagement with the Cross-Cutting Priorities of the Organization” a “Engagement with the Cross-Cutting themes of the Organization”.
- Step 4 “Relevance/Recognition/Engagement”
Cambiar el texto “*In your opinion, PAHO's Technical Cooperation was planned considering the cross-cutting approach (Human Rights, Gender Equity and Ethnicity (Cultural Diversity))?” a “*In your opinion, PAHO's Technical Cooperation was planned considering the Cross-Cutting themes (equity, gender, ethnicity, and human rights)?”
- Step 5  “Multimedia/Conclusion”
En la interface para subir documentos, cambiar el título de la tercera columna de “Actions” a "View"
- Step 5  “Multimedia/Conclusion”
Debajo del título Multimedia agregar como subtexto lo siguiente: “The submitter must declare that each image provided has copyright permission to allow PAHO to use the image if the BP is approved. Please note that you might not be able to delete a file once uploaded.”
- Step 5  “Multimedia/Conclusion”
Cambiar el texto “Select DeCS descriptors (Health Sciences Descriptors):” a “Please select from three to ten keywords that best describe your Best Practice.”
- Step 5  “Multimedia/Conclusion”
Cambiar el texto del último text box de “*What were the lessons learned that will improve our expertise and add value to the Organization?” a “What were the lessons learned you would consider important for an institution and for PAHO's Technical Cooperation to learn from and adapt the Best Practice?”

En el step de "Analyze Best Practice", detallamos los siguientes cambios:

- Cambiar el nombre del título de la página de "Analyze Best Practice" a "Basic Screening"
- Cambiar el nombre del tab "Analyze" a "Basic Screening."
![image](https://user-images.githubusercontent.com/124937355/219487954-cffe5e5b-7fcc-48a0-9705-110d35b4ad7f.png)

En la página "Dashboard" (https://admin.bestpractices.bvsalud.org/), detallamos los siguientes cambios:
- Cambiar el título “Last best practice in which you are part of the research team” a “Recent Best Practices”
![image](https://user-images.githubusercontent.com/124937355/219488910-8a011551-f474-4e60-9f5a-41fb8e57856b.png)

En la etapa de "End Review", detallamos los siguientes cambios:

- En el campo Final Decision, las opciones y sus respectivos status deben cambiarse de la siguiente manera:
- La opción "Not approved" cambia a "Rejected"
- La opción "Observations to Address" cambia a "Revisions required"
- La opción de "Approved" queda igual, sin cambios

A nivel de sistema, detallamos los siguientes cambios:
- El status "Waiting for Committee" debe de ser cambiado a "Waiting for Technical Assessment".

Estamos a la orden para cualquier duda o aclaración que necesites.

Atentamente,
Augusto/Isabella/Jessica

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

NOTA: sobre el ajuste en la opción "Not approved", cabe destacar que el status "Rejected" se utiliza como opción en el paso de Basic Screening. Por lo tanto, recomendamos mantener el nombre actual (Not approved) o cambiarlo por otra etiqueta, para que no haya confusión en la identificación de los status disponibles actualmente.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Gracias por las actualizaciones. Con respecto a los cambios ya realizados, tenemos las siguientes notas:

- Step 5 "Multimedia/Conclusion"
El texto "The submitter must declare that each image provided has copyright permission to allow PAHO to use the image if the BP is approved. Please note that you might not be able to delete a file once uploaded." se muestra justo al lado del titulo, haciendolo parecer que es el texto del help icon.
Sería posible moverlo para que se muestre debajo del título?

- Step 6: “Sources/Comments”
El texto “Please provide comments for the PAHO’s Best Practices Secretariat (Optional)” quedó con un "?" al final, por favor cambiar a dos puntos " : " 

Con respecto al ajuste de la opción "Not Approved" queríamos saber - dejar las opciones con el mismo nombre podría causar confusiones/problemas para futuras actualizaciones para tí u otro programador? O la consideración era más para evitar confusion en el usuario?

**Comment by wilsonmoura** [comment]
@AugustoBaron aquí hay algunos comentarios:

- Step 5 "Multimedia/Conclusion"
El texto "The submitter must declare that each image provided has copyright permission to allow PAHO to use the image if the BP is approved. Please note that you might not be able to delete a file once uploaded." se muestra justo al lado del titulo, haciendolo parecer que es el texto del help icon. Sería posible moverlo para que se muestre debajo del título?
**Creo que su navegador mantuvo el caché anterior para esa página. Recomendamos borrar el caché en esta página (Shift+F5) para mostrar el diseño correctamente.**

- Step 6: “Sources/Comments”
El texto “Please provide comments for the PAHO’s Best Practices Secretariat (Optional)” quedó con un "?" al final, por favor cambiar a dos puntos " : " 
**Hicimos los ajustes requeridos.**

- Con respecto al ajuste de la opción "Not Approved" queríamos saber - dejar las opciones con el mismo nombre podría causar confusiones/problemas para futuras actualizaciones para tí u otro programador? O la consideración era más para evitar confusion en el usuario?
**Creemos que dejar las opciones con el mismo nombre podría causar confusiones en el usuario, ya que son cosas distintas. Actualmente, el status "Rejected" significa que la mejor práctica enviada no ha pasado el paso Basic Screening, y el estado "Not approved" significa que la buena práctica presentada fue evaluada por los revisores y no fue aprobada.**

**Comment by AugustoBaron** [comment]
@wilsonmoura , gracias por la respuesta.
- Step 5 "Multimedia/Conclusion"
El texto "The submitter must declare that each image provided has copyright permission to allow PAHO to use the image if the BP is approved. Please note that you might not be able to delete a file once uploaded." se muestra justo al lado del titulo, haciendolo parecer que es el texto del help icon. Sería posible moverlo para que se muestre debajo del título?
-- Creo que su navegador mantuvo el caché anterior para esa página. Recomendamos borrar el caché en esta página (Shift+F5) para mostrar el diseño correctamente.
-- **Efectivamente, el caché era el culpable. Gracias.**

- Step 6: “Sources/Comments”
El texto “Please provide comments for the PAHO’s Best Practices Secretariat (Optional)” quedó con un "?" al final, por favor cambiar a dos puntos " : "
-- Hicimos los ajustes requeridos.
-- **Gracias.**

- Con respecto al ajuste de la opción "Not Approved" queríamos saber - dejar las opciones con el mismo nombre podría causar confusiones/problemas para futuras actualizaciones para tí u otro programador? O la consideración era más para evitar confusion en el usuario?
-- Creemos que dejar las opciones con el mismo nombre podría causar confusiones en el usuario, ya que son cosas distintas. Actualmente, el status "Rejected" significa que la buena práctica enviada no ha pasado el paso Basic Screening, y el estado "Not approved" significa que la buena práctica presentada fue evaluada por los revisores y no fue aprobada.
-- **En conjunto con los cambios de la prioridad 6, se tiene pensado homogenizar el lenguaje de las decisiones - particularmente las negativas, para evitarle al usuario aprender más. Ambas etapas de evaluación (Basic Screening y Technical Assessment) deberían acabar usando "Rejected" y "Revisions required" con iguales funciones una vez que se implementen. Consideramos que le facilitará al usuario comprender de manera más inmediata que pasó con su buena práctica, complementando con mensajes estándar de nuestra parte para suplir el contexto sobre el nivel de progresión.**

**Comment by wilsonmoura** [comment]
@AugustoBaron gracias tambiém por la respuesta.

- En conjunto con los cambios de la prioridad 6, se tiene pensado homogenizar el lenguaje de las decisiones - particularmente las negativas, para evitarle al usuario aprender más. Ambas etapas de evaluación (Basic Screening y Technical Assessment) deberían acabar usando "Rejected" y "Revisions required" con iguales/similares funciones una vez que se implementen. Consideramos que le facilitará al usuario comprender de manera más inmediata que pasó con su buena práctica, complementando con mensajes estándar de nuestra parte para suplir el contexto sobre el nivel de progresión.
  - **Luego creemos que estos cambios en el status de buenas prácticas se estandarizarán después de los cambios de la prioridad 6. Pero cabe destacar que tendremos esta misma situación con el status "Approved", ya que este status también tiene diferentes significados dependiendo del paso en el que se asigna. En el paso Basic Screening, significa que las buenas prácticas han sido aceptadas y serán evaluadas por los revisores. En el paso End Review, significa que la buena práctica fue evaluada por los revisores y de hecho fue aprobada.**

**Comment by AugustoBaron** [comment]
@wilsonmoura 
- Luego creemos que estos cambios en el status de buenas prácticas se estandarizarán después de los cambios de la prioridad 6. Pero cabe destacar que tendremos esta misma situación con el status "Approved", ya que este status también tiene distintos significados dependiendo del paso en el que se asigna. En el paso Basic Screening, significa que las buenas prácticas han sido aceptadas y serán evaluadas por los revisores. En el paso End Review, significa que la buena práctica fue evaluada por los revisores y de hecho fue aprobada.
-- **Comprendo su punto, sin embargo, no creo que tengamos ese problema ya que al aprobarse a nivel de Basic Screening, el usuario mirará "Waiting for Technical Assessment" como nuevo status. El status "Approved" como tal es únicamente visible cuando es publicada al final. La opción "Approved" del Basic Screening quedará solo como un tecnisimo interno para el Secretariat.**

**Comment by wilsonmoura** [comment]
@AugustoBaron 

- Comprendo su punto, sin embargo, no creo que tengamos ese problema ya que al aprobarse a nivel de Basic Screening, el usuario mirará "Waiting for Technical Assessment" como nuevo status. El status "Approved" como tal es únicamente visible cuando es publicada al final. La opción "Approved" del Basic Screening quedará solo como un tecnisimo interno para el Secretariat.
  **- Hicimos los ajustes requeridos.**

**Comment by AugustoBaron** [comment]
@wilsonmoura 

Corroboramos que los cambios solicitados están listos para la versión live. Muchas gracias!
