### ISSUE TITLE
Correos automáticos

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#69]
Estimado Wilson,

Continuando con la lista de prioridades, en quinto lugar hemos establecido los siguientes ajustes con respecto a los correos automáticos (https://admin.bestpractices.bvsalud.org/admin/mail):

- El correo ID 4 está escrito para ser dirigido al usuario para informarle que su cuenta fue activada. Sin embargo, parece que la interacción no está funcionando. Cuando se activa una cuenta, el usuario no recibe ningún correo por el momento.
- Actualmente, el usuario no recibe un correo de confirmación cuando reenvía su form después que se le fue devuelta con las opciones de "Reject submission" en Analyze u "Observations to address" en End Review. 
- El token %protocol_url% actualmente se dirige al "See Best Practices" menu. Queremos solicitar que envíe en su lugar a la página de "Edit Submission".
- Actualmente, el correo ID 8 se le envía al Secretariat para avisar que un nuevo usuario se ha registrado y procesar la activación de la cuenta - sin embargo, no incluye detalles de quien acaba de registrarse. Queremos solicitar que este correo incluya algún tipo de token que permita identificar el nombre del usuario que acaba de registrarse.
- Las parejas de correos ID 1 y 17 / 7 y 3 / 11 y 2 tienen el mismo contenido, quisieramos que se pudiese revisar a que interacciones están ligados, porque si no tal vez podría dejarse un único correo y eliminar, o cambiar el propósito del que no está funcionando. De estas parejas logramos determinar que los siguientes correos duplicados se encuentran inactivos: ID 1, 3 y 11.
- No encontramos la función de los correos ID 10, 12, 13, 14 - quisiéramos confirmar si estos están funcionales o solo se encuentran como remanentes de ProEthos. 
- El correo ID 18 para notificar sobre un nuevo comentario añadido debería de ser notificado también al rol Submitter.

Estamos a la orden para cualquier duda o aclaración que necesites.

Atentamente,
Augusto/Isabella/Jessica

**Comment by wilsonmoura** [comment]
@AugustoBaron aquí hay algunos comentarios:

- El correo ID 4 está escrito para ser dirigido al usuario para informarle que su cuenta fue activada. Sin embargo, parece que la interacción no está funcionando. Cuando se activa una cuenta, el usuario no recibe ningún correo por el momento.
  - **Les pedimos que realicen nuevas pruebas, ya que hicimos algunas pruebas y este correo funcionó correctamente.**
- Actualmente, el usuario no recibe un correo de confirmación cuando reenvía su form después que se le fue devuelta con las opciones de "Reject submission" en Analyze u "Observations to address" en End Review.
  - **Hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/**
- El token %protocol_url% actualmente se dirige al "See Best Practices" menu. Queremos solicitar que envíe en su lugar a la página de "Edit Submission".
  - **Para facilitar las cosas, hemos agregado el token `%edit_submission_url%` para mostrar el enlace a la página de edición.**
- Actualmente, el correo ID 8 se le envía al Secretariat para avisar que un nuevo usuario se ha registrado y procesar la activación de la cuenta - sin embargo, no incluye detalles de quien acaba de registrarse. Queremos solicitar que este correo incluya algún tipo de token que permita identificar el nombre del usuario que acaba de registrarse.
  - **Ahora también es posible utilizar el token `%username%` para mostrar el nombre de usuario en el correo ID 8.**
- Las parejas de correos ID 1 y 17 / 3 y 7 / 2 y 11 tienen el mismo contenido, quisieramos que se pudiese revisar a que interacciones están ligados, porque si no tal vez podría dejarse un único correo y eliminar, o cambiar el propósito del que no está funcionando. De estas parejas logramos determinar que los siguientes correos duplicados se encuentran inactivos: ID 1, 3 y 11.
  - **El correo ID 1 se utilizó en una funcionalidad específica del sistema ProEthos, es decir, ya no es necesario y lo vamos a eliminar de la lista de correos.**
  - **El correo ID 3 se envía cuando se crean nuevos usuarios en el sistema por usuarios con el perfil de Secretariat en el menú `Committee >> Users >> New User`.**
  - **El correo ID 3 se envía cuando el Submitter envía una buena práctica, y el correo ID 11 se envía cuando se aprueban buenas prácticas en la etapa de Basic Screening. Pero en ambos casos, el texto del asunto del correo es el mismo: "Your best practice was sent to review". La sugerencia es cambiar el texto del asunto del correo ID 11 a "Your best practice was sent to evaluation".**
- No encontramos la función de los correos ID 10, 12, 13, 14 - quisiéramos confirmar si estos están funcionales o solo se encuentran como remanentes de ProEthos. 
  - **Los correos ID 10, 12, 13 y 14 se utilizaron en funcionalidades específicas del sistema ProEthos, es decir, ya no son necesarios y los eliminaremos de la lista de correos.**
- El correo ID 18 para notificar sobre un nuevo comentario añadido debería de ser notificado también al rol Submitter.
  - **Hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/**

**Comment by AugustoBaron** [comment]
@wilsonmoura Gracias por el follow-up. Después de hacer otras pruebas he encontrado lo siguiente:
- El correo ID 4 está escrito para ser dirigido al usuario para informarle que su cuenta fue activada. Sin embargo, parece que la interacción no está funcionando. Cuando se activa una cuenta, el usuario no recibe ningún correo por el momento.
-- Les pedimos que realicen nuevas pruebas, ya que hicimos algunas pruebas y este correo funcionó correctamente.
-- **Hemos vuelto a probar en ambas plataformas, encontramos ya que el correo en efecto funciona. Inmediatamente si es outlook, pero es inconstante si es Yahoo. Por eso la confusión.**

- Actualmente, el usuario no recibe un correo de confirmación cuando reenvía su form después que se le fue devuelta con las opciones de "Reject submission" en Analyze u "Observations to address" en End Review.
-- Hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/
-- **El Submitter recibe ahora correctamente un correo de confirmación cada vez que se vuelve a enviar, gracias.**

- El token %protocol_url% actualmente se dirige al "See Best Practices" menu. Queremos solicitar que envíe en su lugar a la página de "Edit Submission".
-- Para facilitar las cosas, hemos agregado el token %edit_submission_url% para mostrar el enlace a la página de edición.
-- **El nuevo token funciona adecuadamente, gracias.**

- Actualmente, el correo ID 8 se le envía al Secretariat para avisar que un nuevo usuario se ha registrado y procesar la activación de la cuenta - sin embargo, no incluye detalles de quien acaba de registrarse. Queremos solicitar que este correo incluya algún tipo de token que permita identificar el nombre del usuario que acaba de registrarse.
-- Ahora también es posible utilizar el token %username% para mostrar el nombre de usuario en el correo ID 8.
-- **El token %username% ha funcionado correctamente en el ID 8.**

- Las parejas de correos ID 1 y 17 / 3 y 7 / 2 y 11 tienen el mismo contenido, quisieramos que se pudiese revisar a que interacciones están ligados, porque si no tal vez podría dejarse un único correo y eliminar, o cambiar el propósito del que no está funcionando. De estas parejas logramos determinar que los siguientes correos duplicados se encuentran inactivos: ID 1, 3 y 11.
--El correo ID 3 se envía cuando se crean nuevos usuarios en el sistema por usuarios con el perfil de Secretariat en el menú Committee >> Users >> New User.
-- **Gracias por la confirmación.**
--El correo ID 2 se envía cuando el Submitter envía una nueva buena práctica, y el correo ID 11 se envía cuando se aprueban buenas prácticas en la etapa de Basic Screening. Pero en ambos casos, el texto del asunto del correo es el mismo: "Your best practice was sent to review". La sugerencia es cambiar el texto del asunto del correo ID 11 a "Your best practice was sent to evaluation".
-- **Gracias por la confirmación. Creemos que sería ideal cambiar el asunto del ID 11 a `"Your Best Practice was sent for Technical Assessment"`**

- El correo ID 18 para notificar sobre un nuevo comentario añadido debería de ser notificado también al rol Submitter.
-- Hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/
-- **Según las pruebas, el Submitter sigue sin recibir una notificación, solo el Secretariat.**

**Comment by wilsonmoura** [comment]
@AugustoBaron

- Creemos que sería ideal cambiar el asunto del ID 11 a `"Your Best Practice was sent for Technical Assessment"`
  - **Hicimos los ajustes requeridos**
- El correo ID 18 para notificar sobre un nuevo comentario añadido debería de ser notificado también al rol Submitter. Según las pruebas, el Submitter sigue sin recibir una notificación, solo el Secretariat.
  - **Les pedimos que realicen nuevas pruebas, ya que hicimos algunas pruebas y este correo funcionó correctamente.**

**Comment by AugustoBaron** [comment]
@wilsonmoura  Gracias por los cambios.

- Creemos que sería ideal cambiar el asunto del ID 11 a "Your Best Practice was sent for Technical Assessment"
-- Hicimos los ajustes requeridos
-- **El título actualizado dice "was sent to", solicitamos que se cambie a "was sent for". Eso ya sería lo último.** 

- El correo ID 18 para notificar sobre un nuevo comentario añadido debería de ser notificado también al rol Submitter. Según las pruebas, el Submitter sigue sin recibir una notificación, solo el Secretariat.
-- Les pedimos que realicen nuevas pruebas, ya que hicimos algunas pruebas y este correo funcionó correctamente.
-- **Disculpas, estábamos esperando verlo un correo aparte. Ya corroboramos que efectivamente se incluye al Submitter en la lista de envío.**

**Comment by wilsonmoura** [comment]
@AugustoBaron

- El título actualizado dice "was sent to", solicitamos que se cambie a "was sent for". Eso ya sería lo último.
  - **Hicimos los ajustes requeridos.**

**Comment by AugustoBaron** [comment]
@wilsonmoura 

Corroboramos que todos los cambios están listos para la versión live. Muchas gracias por su apoyo.
