### ISSUE TITLE
Adición/Eliminación de Campos

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#70]
Estimado Wilson,

Continuando con la lista de prioridades, en sexto lugar hemos establecido los siguientes ajustes:

**0. Eliminar campo "Other information sources" del submission form**
- Eliminar el campo "Other information sources (hyperlinks only):” en el Step 6 “Sources/
Comments” del Submission Form:
![image](https://user-images.githubusercontent.com/124937355/220985008-688784d1-0e86-4564-ae54-8b072a16be90.png)

**1. Generar en el PDF el disclaimer de Términos y Condiciones:**
Agregar en el PDF generado al final del Submission form la información sobre los términos y condiciones que fueron aceptados por el usuario:
![image](https://user-images.githubusercontent.com/124937355/220985465-add2c4fe-ba77-4f2d-b086-8330ff36b31c.png)

El texto generado en el PDF debería leer:

“Terms and Conditions”
“**[Importar aquí el primer nombre y primer apellido]** agreed with the Terms of Use and Privacy Policy of PAHO’s Best Practices Portal the **[Poner aquí la fecha]** at **[Poner aquí la hora en formato 24 horas]**, having read the following text:

I agree with the Terms of Use and Privacy Policy
•	All contributions must be original. Contributors warrant that they have the necessary rights, including the necessary licenses, for the use of any copyrighted material in the submission. Furthermore, contributors warrant that all necessary permissions and consents have been obtained for all materials depicting identifiable human subjects.
•	By submitting a contribution, contributors grant PAHO and related partners a free perpetual non-exclusive license to use, edit and publish the contribution for noncommercial purposes.
•	Contributors agree to identify, defend, and hold PAHO and related partners harmless from any actions or claims brought against them pertaining to the alleged infringement arising in connection with the contribution.
•	PAHO and related partners reserve the right, at their sole discretion, to determine which contributions will be included in the portal or used in other institutional material.
•	By submitting this contribution, contributors confirm that they have read, understood, and accepted these conditions.”

**2. Agregar una nueva acción en el Basic Screening (“Analyze Best Practices” menu).**
Actualmente, el analyze/basic screening tiene estas opciones: 
![image](https://user-images.githubusercontent.com/124937355/220987051-546224a2-00ab-44da-8b73-a4d898738995.png)
Solicitamos lo siguiente:
- Cambiar el texto de "Accept Submission" a "Approved".
- Agregar un nuevo text box "Comments:" que aparezca cuando se selecciona "Approved". Los contenidos de este text box deberían de ser visibles para el usuario (Rol "Submitter") en un recuadro de color verde al abrir "See Best Practices":
![image](https://user-images.githubusercontent.com/124937355/220988506-fc918e6c-ff7a-4334-817f-99a715a7622f.png)
El botón "Send to revision" que aparece al seleccionar la opción actualmente nombrada como "Accept Submission" debe de ser renombrado a "Send to review":
![image](https://user-images.githubusercontent.com/124937355/220989308-fdf1080f-de52-4600-b106-1e44bbe4eb3b.png)
- Cambiar el texto de la opción de "Reject Submission" a "Revisions required" y su status correspondiente de "Rejected" a "Revisions required".
- El botón "Send back to Investigator" que aparece al seleccionar la opción actualmente nombrada como "Reject Submission" debe de ser renombrado a "Send back to Submitter":
![image](https://user-images.githubusercontent.com/124937355/220989346-22caa9bd-d741-450f-810b-3da8f4d4fcae.png)
- Agregar una nueva tercera opción de nombre "Rejected" que tenga las mismas funciones que "Withdraw Submission" pero que use el status de nombre "Rejected". Seleccionar esta opción, deberá abrir un text box "Rejection reasons:" y este texto deberá de ser visible al usuario en un recuadro de color rojo en la página "Show Best Practice":
![image](https://user-images.githubusercontent.com/124937355/220990535-1c6e0980-f261-4d45-9554-edefe0a37895.png)
Esta opción deberá utilizar un botón de confirmación con el texto "Reject Submission". Esta opción deberá también generar su propio correo automático. 
Mock-up:
![image](https://user-images.githubusercontent.com/124937355/221003130-03982fb5-0004-47a7-bd24-8ae14c895eed.png)

**3. Cambios en los campos de "Reviewer's evaluation" durante la etapa de Initial Review Committee/Technical Assessment para los usuarios de rol "Reviewer"**
![image](https://user-images.githubusercontent.com/124937355/220991437-14096170-5f82-4c81-ba2f-a829bd66306c.png)
Este cambio debe de tenerse en consideración como un cambio temporal mientras la prioridad 8 es finalizada.
El campo "Decisions" debe pasar a un campo de breakdown list, con las siguientes opciones:
- Approved
- Rejected
- Revisions required 
El campo "Suggestions:" debe de ser renombrado a "Recommendations:"

**4. Cambio en el campo "Final Decision" durante el "End Review" para los usuarios de rol "Secretariat"**
Actualmente este campo se visualiza de la siguiente manera:
![image](https://user-images.githubusercontent.com/124937355/220992424-c84a5c27-1f75-4e7a-bac0-49c45e9807a3.png)
Las opciones de este campo y sus status deben de ser renombrados de la siguiente manera:
- "Not approved" debe cambiarse a "Rejected"
- "Observations to address" debe cambiarse a "Revisions required"
Actualmente seleccionar cualquiera de las tres opciones envía el mismo tipo de correo automático. Se solicita que se cambie a que cada opción envíe su correo automático específico. Estos correos deberán de ser versiones nuevas y no ligados a los correos de la etapa de "Analyze"/"Basic Screening".

**5. Agregar la función de comentarios confidenciales y subida de archivos confidenciales para las cuentas con el rol de "Secretariat" o crear una nuevas secciones confidenciales.**
**Comentarios:**
Actualmente, solo las cuentas con el rol "Reviewer" (Member of the Committee) tienen acceso a la opción de "Mark as Confidential" cuando desean agregar un nuevo comentario. Se solicita añadir esta opción para los miembros del Secretariat o crear una nueva sección llamada "Comments (Confidential)" visible solo para el Secretariat:
![image](https://user-images.githubusercontent.com/124937355/220994694-2ce8fcd3-74e7-41e7-9fff-88484129e819.png)

**Subida de archivos/File upload:**
Actualmente no existen opciones para subir documentos de manera confidencial por parte de los reviewers o el Secretariat. Se solicita añadir la opción de "Mark as Confidential" cuando se intenta subir un nuevo documento en la sección de "File submission":
![image](https://user-images.githubusercontent.com/124937355/220995267-a19d07f7-7412-4864-8874-8fbf9540e80d.png)
Mock-up:
![image](https://user-images.githubusercontent.com/124937355/220995395-5092ee17-1e0b-418c-a4c1-9d17c19b3983.png)
Y que los documentos agregados de manera confidencial lleven algún tipo de identificador como ser un asterisco en el nombre.
Si esto puede ser muy complicado, se solicita en su lugar agregar una nueva sección llamada "File submission (Confidential)" visible solo para los usuarios con el rol "Secretariat".

**6. Agregar un disclaimer en la página del submission form**
Agregar el siguiente texto como disclaimer en la página del submission form principal entre el título "New submission" y las tabs:
IMPORTANT
Your session will automatically expire after two hours if the page is not manually saved. To avoid any loss of information, it is recommended to periodically save your progress using the ‘Save and Next’ button
Se busca que se mire más o menos así:
![image](https://user-images.githubusercontent.com/124937355/220996088-d3d48634-7fbe-4ede-8901-064aad231869.png)

**7. Agregar enlaces rápidos para los reviewers**
Para los usuarios de rol "Reviewer" cuando entran a revisar una buena práctica en su página Initial committeee review, entre el título y las tabs se debería de incluir un pequeño campo en el cual aparezcan todos los links que en la página de Documents (https://admin.bestpractices.bvsalud.org/committee/documents) se le hayan asignado al rol "Reviewer".
Asimismo, se solicitan los siguientes cambios de texto:
- El título "Initial committee review" y el nombre del tab debe de ser cambiado a "Technical Assessment". 
Pequeño mock-up:
![image](https://user-images.githubusercontent.com/124937355/220998546-b3ebda4c-815b-4ca2-9bde-42e7aeb27b86.png)
- El nombre del botón para acceder a esta página debe de cambiar de "Initial Committee Review" a "Technical Assessment"
![image](https://user-images.githubusercontent.com/124937355/220999026-8c5512a6-5523-402b-bbfd-0d5812caeb46.png)

 **8. Cambios en la sección "Reviewers" en la página "Initial Review Committee" para las cuentas de rol "Secretariat"**
- El título "Initial committee review" y el nombre del tab debe de ser cambiado a "Technical Asessment".
Sobre la siguiente sección:
![image](https://user-images.githubusercontent.com/124937355/221000119-19f09a52-776a-45aa-8e91-0c373e798bed.png)
- El botón “Select Members of Committee” debe de ser renombrado a “Select Reviewers (Committee/Ad Hoc)”.
- El botón "Select members Ad-Hoc" debe de ser eliminado.
Sobre la ventana de selección de reviewers:
- El título "Select Members of Committee" debe pasar a “Select Reviewers (Committee/Ad Hoc)"
- Agregar una barra de búsqueda en la ventana para buscar reviewers por nombre, institución o email de la siguiente manera:
![image](https://user-images.githubusercontent.com/124937355/221000574-8217da37-e44b-42e9-870c-5d236b81e036.png)
- El botón "Save and Send to Meeting" deberá cambiarse a "Save and make Final Decision" - el status asociado a esta interacción deberá pasar de "Scheduled" a "Waiting for Final Decision".

**9. Cambios en el step 7 "Review" del submission form**
- Cambiar el título de "Revision:" a "Review your proposal:"
- Agregar entre el título y la tabla del checklist de los campos obligatorios una tabla con la leyenda de que significa cada símbolo de la siguiente manera:
![image](https://user-images.githubusercontent.com/124937355/221001576-ad630e1a-6484-4af1-b75a-540fdef58c19.png)

**10. Submission form**
- En el Submission form, en el tab del step 3 
![image](https://user-images.githubusercontent.com/124937355/223759413-9a223655-7279-4ec5-a6ed-73c84bab6c6c.png)
y en el primer título 
![image](https://user-images.githubusercontent.com/124937355/223760101-9bb0cffc-cc7f-4695-b4a9-8698920f96ca.png)
cambiar "Cost-Effectivess" a "Cost-Effectiveness".

Estamos a la orden para cualquier duda o aclaración que necesites.

Atentamente,
Augusto/Isabella/Jessica

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

Aquí hay algunos comentarios:

- **Actividad 4:**
  - Con respecto a este tema, ajustamos los correos de acuerdo con la decisión final:
    - Correo ID 12: Approved
    - Correo ID 13: Revisions required
    - Correo ID 14: Rejected
- **Actividad 5:**
  - Con respecto a los comentarios, hicimos algunas pruebas y la función de comentarios confidenciales funcionó correctamente. Cabe mencionar que existe una regla en el sistema que impide que el Submitter envíe comentarios confidenciales. Todavía en este tema, agregamos una nueva columna (visible solo para los perfiles de Secretariat y Reviewer) para que sea posible identificar comentarios confidenciales.
  - Con respecto a los uploads, ahora es posible cargar archivos confidenciales. Todavía en este tema, agregamos una nueva columna (visible solo para los perfiles de Secretariat y Reviewer) para que sea posible identificar los uploads confidenciales.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura,

Gracias por el follow-up, de acuerdo con nuestras pruebas:

Actividad 0:
- El text box ha sido correctamente borrado.

Actividad 1:
- El PDF genera adecuadamente el disclaimer del Terms and Conditions - quedó excelente!

Actividad 2:
Hemos observado los siguientes puntos que requieren de revisión:
- La opción "Revisions Required" no tiene el text box  "Return reason". 
- Si se aplica la opción "Revisions Required" en el Basic Screening y se usa el botón `Retrieve best practice` la buena práctica "regresa" al step de `Waiting for Final Decision` en vez del step `Submitted`.
- Notamos que pareciese que esta opción en vez de ser la opción vieja de "Reject submission" solo que con nombre diferente, es una nueva basada en el "Revisions required" del Technical Assessment. Creemos adecuado solicitar que por favor se reinstaure la opción de reject submission vieja solo que con el nombre de Revisions required. Siempre se desea que esta opción mantenga el text box de return reason que se le muestre al submitter en el text box naranja en la página de Edit Submission como antes.

Actividad 3:
- No se logró valorar ya que al intentar asignar Reviewers aquí:
![image](https://user-images.githubusercontent.com/124937355/224754916-f526afe1-4db8-450d-9745-c391f702985b.png)
la página solo mostró el siguiente error:
![image](https://user-images.githubusercontent.com/124937355/224755245-30c4c39a-baf9-4719-a02e-2a6d08a96c7c.png)
El error se mostró independientemente de quién era elegido como reviewer y de la cantidad.

Actividad 4: 
- Los correos ID 12, 13, 14 se envían adecuadamente.
- Notamos que al `Approve` o `Reject` una best practice genera el text box de notes con el color asociado como en el Basic Screening. Consideramos que si estas opciones van a generar estos text box en la página de See Best Practice, entonces debería estar el text box visible en `Final Decision` para poder escribir una razón. De lo contrario, consideramos que sería mejor que **solo** para las decisiones de Final Decision, no aparezcan esos text boxes - pero mantenerlas en Basic Screening.
Otra alternativa plausible, sería que la interfase de decisión de Basic Screening y Technical Assessment tengan el mismo estilo visualmente, con sus tres opciones y tres text boxes asociadas. Pero con las funciones específicas de cada una.

Actividad 5:
- De acuerdo a nuestras pruebas el rol Submitter puede ver los archivos subidos de manera confidencial cuando deberían de estar ocultos. 

Actividad 6: 
- Se observa que el text box se muestra adecuadamente en el submission form

Actividad 7:
- Igual que en la act 3, no es posible valorarla en este momento debido al error del servidor que se muestra.

Actividad 8:
- Los cambios del texto están adecuados
- La funcionalidad del filtro en la selección de los reviewers está excelente, muchas gracias.
- Al apretar el botón "Save" se genera el error del servidor descrito en la Actividad 3.

Actividad 9:
- La leyenda se visibiliza adecuadamente.

Actividad 10:
- El cambio de texto ha sido correctamente adecuado.


Quedamos atentos para poder continuar trabajando contigo cuando vuelvas. Boas férias!

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos más algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by wilsonmoura** [comment]
@AugustoBaron aquí hay más algunos comentarios:

- Actividad 2:
  - Usar el botón de "Retrieve Submission" en una BP que fue seleccionada como Revisions Required a nivel del Basic Screening, aún enviará la propuesta al step "Waiting for Final Decision" en vez de "Submitted".
    - **En el sistema original, el botón "Retrieve Submission" sirve únicamente para que los usuarios con el rol Secretariat recuperen el control de la respectiva propuesta, sin tener la necesidad de volver a pasar por todo el proceso de selección y revisión de los miembros del comité, ya que existe la posibilidad de que un usuario con el rol Secretariat asigne erróneamente una decisión de una propuesta. Por lo tanto, cuando activamos la función "Retrieve Submission", la propuesta vuelve al step "Waiting for Final Decision" en vez de "Submitted".**
- Actividad 5:
  - Los archivos subidos en File submission como confidenciales siguen siendo visibles tanto por el Submitter y el Reviewer. Solo el Secretariat debe tener acceso a ellos. Si no es posible impedir que los archivos individuales puedan ser vistos (o hay una preocupación sobre si ocultarlos podría hacer creer a la gente que no se subió el archivo correctamente), tal vez otra solución sería desactivar el botón para "Ver" para los roles Reviewer y Submitter.
    - **Hicimos más algunos ajustes. Por favor, haga más algunas pruebas.**

**Comment by AugustoBaron** [comment]
@wilsonmoura - Gracias por el follow-up

Actividad 2:

- Usar el botón de "Retrieve Submission" en una BP que fue seleccionada como Revisions Required a nivel del Basic Screening, aún enviará la propuesta al step "Waiting for Final Decision" en vez de "Submitted".
- En el sistema original, el botón "Retrieve Submission" sirve únicamente para que los usuarios con el rol Secretariat recuperen el control de la respectiva propuesta, sin tener la necesidad de volver a pasar por todo el proceso de selección y revisión de los miembros del comité, ya que existe la posibilidad de que un usuario con el rol Secretariat asigne erróneamente una decisión de una propuesta. Por lo tanto, cuando activamos la función "Retrieve Submission", la propuesta vuelve al step "Waiting for Final Decision" en vez de "Submitted".
- **Había entendido que la función del botón era anular la decisión de regresar la BP al Submitter y devolverla a la etapa en la que estaba. He probado en la versión live que aún tiene los parámetros originales, y si se usa el botón de `Retrieve submission` cuando la BP es rechazada a nivel del Basic Screening si regresa al status `Submitted` en vez de enviarla directamente a la última etapa. ¿Es posible recuperar esta funcionalidad? Ya que podría causar problemas si una BP es retrieved a nivel del Basic Screening y queda atrapada en el proceso de decisión final sin tener la posibilidad de regresarla a etapas anteriores.** 

Actividad 5:

- Los archivos subidos en File submission como confidenciales siguen siendo visibles tanto por el Submitter y el Reviewer. Solo el Secretariat debe tener acceso a ellos. Si no es posible impedir que los archivos individuales puedan ser vistos (o hay una preocupación sobre si ocultarlos podría hacer creer a la gente que no se subió el archivo correctamente), tal vez otra solución sería desactivar el botón para "Ver" para los roles Reviewer y Submitter.
- Hicimos más algunos ajustes. Por favor, haga más algunas pruebas.
- **Los archivos confidenciales ahora si están visibles solo para el Secretariat. Gracias!**

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos más algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org

**Nota:** Para que las pruebas funcionen correctamente, se recomienda enviar una nueva propuesta.

**Comment by AugustoBaron** [comment]
@wilsonmoura, se han realizado nuevas pruebas. El botón Retrieve Submission ahora correctamente regresa la BP a la etapa anterior.

Muchas gracias.
