### ISSUE TITLE
Cambios en los permisos

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#71]
Estimado Wilson,

Como séptima prioridad, hemos identificado la necesidad de alterar los siguientes permisos en el sistema:
- El acceso a la página FAQ (https://admin.bestpractices.bvsalud.org/public/faq) debe deshabilitarse por el momento. No eliminarse, solo esconder el link por ahora.
- Actualmente en la página de los usuarios "Users" (https://admin.bestpractices.bvsalud.org/committee/users) tanto los usuarios con el rol de Secretariat como Administrator pueden usar el botón "Edit roles". Solicitamos que se inhabilite el uso de ese botón al rol "Secretariat" y solo quede para los usuarios que tengan el rol de "Administrator".
- Actualmente cuando se le devuelve una submission al Submitter, en la sección de "Multimedia/Conclusion" el submitter puede borrar cualquier archivo, incluyendo versiones pasadas de los PDF del submission form. Se solicita deshabilitar a los usuarios con el rol "Submitter" (Investigator) poder eliminar archivos.

Asimismo, se solicita agregar un pequeño disclaimer en dicha sección: 
"Before uploading please ensure you have selected the proper file, once uploaded you won't be able to delete it. By uploading a file, the Submitter attests that they hold the permission(s) to make use and disseminate its contents through the Best Practices Portal. If any document is mistakenly uploaded and requires deletion, please contact the Secretariat through the "Comments" function (available after sending the submission)."

Mock-up:
![image](https://user-images.githubusercontent.com/124937355/221025362-90a422cf-26f2-4a5d-a025-679585cf15f8.png)

Quedamos a la orden para cualquier duda.

Atentamente,
Augusto/Isabella/Jessica

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

Aquí hay algunos comentarios:

- El acceso a la página FAQ (https://admin.bestpractices.bvsalud.org/public/faq) debe deshabilitarse por el momento. No eliminarse, solo esconder el link por ahora.
  - **Hicimos los cambios requeridos**
- Actualmente en la página de los usuarios "Users" (https://admin.bestpractices.bvsalud.org/committee/users) tanto los usuarios con el rol de Secretariat como Administrator pueden usar el botón "Edit roles". Solicitamos que se inhabilite el uso de ese botón al rol "Secretariat" y solo quede para los usuarios que tengan el rol de "Administrator".
  - **Actualmente, solo el rol Secretariat tiene permisos para acceder el menú `Users`. Creo que hubo cierta confusión al acceder al sistema con un usuario con más de un rol. Asimismo, si es necesario, podemos mover el menú `Users` al menú `System Management`, ya que solo el perfil de Administrador puede acceder a este menú.**
- Actualmente cuando se le devuelve una submission al Submitter, en la sección de "Multimedia/Conclusion" el submitter puede borrar cualquier archivo, incluyendo versiones pasadas de los PDF del submission form. Se solicita deshabilitar a los usuarios con el rol "Submitter" (Investigator) poder eliminar archivos.
  - **Hicimos los ajustes requeridos. Cabe destacar que las versiones pasadas de los PDF del submission form estaban visibles en esta sección debido a un bug en el sistema, pero ya hemos hecho las correcciones necesarias.**

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Con respecto a los ajustes realizados:
- El FAQ lo encontramos correctamente escondido.
- Actualmente en la página de los usuarios "Users" (https://admin.bestpractices.bvsalud.org/committee/users) tanto los usuarios con el rol de Secretariat como Administrator pueden usar el botón "Edit roles". Solicitamos que se inhabilite el uso de ese botón al rol "Secretariat" y solo quede para los usuarios que tengan el rol de "Administrator".
-- Actualmente, solo el rol Secretariat tiene permisos para acceder el menú Users. Creo que hubo cierta confusión al acceder al sistema con un usuario con más de un rol. Asimismo, si es necesario, podemos mover el menú Users al menú System Management, ya que solo el perfil de Administrador puede acceder a este menú.
-- **Hemos considerado que si no es posible adecuar el acceso al botón "Edit roles" de manera específica. Se deje tal como está sin cambios, ya que el Secretariat debe de mantener el acceso a dicha página.**
-Actualmente cuando se le devuelve una submission al Submitter, en la sección de "Multimedia/Conclusion" el submitter puede borrar cualquier archivo, incluyendo versiones pasadas de los PDF del submission form. Se solicita deshabilitar a los usuarios con el rol "Submitter" (Investigator) poder eliminar archivos.
-- Hicimos los ajustes requeridos. Cabe destacar que las versiones pasadas de los PDF del submission form estaban visibles en esta sección debido a un bug en el sistema, pero ya hemos hecho las correcciones necesarias.
-- **Gracias por el feedback. Lo tomaremos en cuenta para un posible futuro ajuste. Sin embargo, según nuestras pruebas observamos que los permisos para borrar documentos han sido correctamente revocados y consideramos que está listo para la versión live.**

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos más algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by AugustoBaron** [comment]
@wilsonmoura Gracias por el follow-up, el subtexto de Multimedia está ahora apropiado. Y la página de Users la dejaremos sin cambios entonces.

Agradecemos mucho los esfuerzos.
