### ISSUE TITLE
Interfaz de Reviewer

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#72]
Estimado Wilson,

Como octava prioridad hemos identificado los cambios a la interfaz que le reviewer tendrá para realizar su evaluación. 

Esta sección deberá de reemplazar lo que los usuarios con el rol de "Reviewer" (Member of the Committee) mirarán en la sección de "Reviewer's decision" de la página "Technical Assessment" (Initial Committee Review) después que se les ha asignado una buena práctica para evaluar.

Esto cambiará esos campos por una interfase a modo de tabla (o forma) en la cual los reviewers podrán obtener información guía, seleccionar una opción de puntaje (Scoring) y seleccionar una opción de (Feedback) por cada uno de los atributos.

He creado un mockup de un atributo para dar una idea ya que los 8 contienen la misma estructura (solo cambia algunos valores en los puntajes):

![reviewerinterface](https://user-images.githubusercontent.com/124937355/221040264-576e3b9f-6062-4a16-9596-99baf5729b8b.png)

Asimismo, esta interfase deberá poder generar un PDF con los inventarios de cambios a realizar, es decir que deberá recabar todo lo que los reviewers escriben en los text boxs de "Revisions required" en la sección de Feedback por cada atributo. De ser posible que se genere automaticamente al enviar la review y esté disponible en el apartado de "File submissions" (visible para todos).
 

Todos los detalles, incluyendo la estructura de la tabla se han recabado en el siguiente documento: 
[P8 - Interfaz de evaluación para reviewers.docx](https://github.com/bireme/ods3-best-practices/files/10818632/P8.-.Interfaz.de.evaluacion.para.reviewers.docx)

Quedamos atentos a cualquier duda.

Atentamente,
Augusto/Isabella/Jessica

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

Aquí hay algunos comentarios:

- En cuanto al botón para generar un archivo PDF con las revisiones necesarias, recomendamos mostrar este botón en el popup de vista previa de revisiones disponible en el paso de Technical Assessment, ya que de esta manera, los usuarios con el rol Secretariat tendrán acceso automático a los archivos PDF de revisiones. La siguiente imagen muestra un ejemplo:

![screenshot-ods3 local bvsalud org-2023 04 13-18_33_22](https://user-images.githubusercontent.com/3779520/231895399-d4a93188-bee5-434b-91a6-50a0f95a6836.png)

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos más algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos más algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/
