### ISSUE TITLE
Interfase de Institutional Review

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#74]
Estimado Wilson,

Por el momento hemos dejado como prioridad 10 las adiciones al sistema con respecto al step de Institutional Review en el submission form y dentro de la interfase de información general. Sin embargo, consideramos que esto retomará un nivel de prioridad más alto en un futuro cercano.

Todos los detalles los hemos recabado en el siguiente documento:
[P10 - FENSA.docx](https://github.com/bireme/ods3-best-practices/files/10818991/P10.-.FENSA.docx)

Los mock ups de las interfase son:
- Para el nuevo step de Institutional Review en el Submission form:
![image](https://user-images.githubusercontent.com/124937355/221043533-7e33c131-e634-4ab7-ad91-9bc8b081fae1.png)
- Para el nuevo tab en la interfase de información general:
![image](https://user-images.githubusercontent.com/124937355/221043736-79e5e3e2-0892-4ced-a8b8-6a2abdd946a0.png)

Quedamos atentos a cualquier duda.

Atentamente,
Augusto/Isabella/Jessica

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura,

Hemos hecho algunas pruebas y hemos notado lo siguiente:
- Al llegar a la etapa "Multimedia/Conclusion" y llenar los campos mandatorios, apretar "Save and Next" se guarda la página pero no continúa a la siguiente etapa:
![image](https://user-images.githubusercontent.com/124937355/232864278-0b7cb614-9d53-40fb-b7df-c3322e58596b.png)
Se probó con keywords agregados, mismo resultado.
Se probó agregar imágenes, pero hubo un error (ver abajo).

- Al intentar subir un documento que no sea una imagen en "Multimedia" en vez de salir solo el mensaje de error esperado:
![image](https://user-images.githubusercontent.com/124937355/232864719-7effc370-60c1-4986-ba99-4184e1fd55eb.png)
la página es redireccionada hacia esta página de error:
![image](https://user-images.githubusercontent.com/124937355/232864817-6e09c31f-f656-425a-b935-4a6d9ba92d57.png)

Al intentar subir una imagen, también sale el mismo error:
![image](https://user-images.githubusercontent.com/124937355/232864946-7a7bac25-5d3c-4cb8-a414-666b12ed0920.png)

- Después de someter la BP, hemos notado que la sección de "Institutional Review" no tiene opción para borrar los archivos y/o agregar nuevos.
Podría agregarse el permiso de borrar archivos solo para los usuarios con el rol de Administrador?
Podría agregarse la opción de subir nuevos archivos a esta sección solo para los usuarios con el rol de Secretariat y/o Administrador?

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura,

Haciendo más tests hemos detectado que al seleccionar una opción que no requiere que aparezca el tab de "Institutional Review" en el submission form, en el tab de "Review" siempre aparecerán los documentos de FENSA como requisitos incompletos:
![image](https://user-images.githubusercontent.com/124937355/233206709-c53d735c-addc-44d1-9716-4fb7a1d61862.png)
Y no permitirá enviar el submission form:
![image](https://user-images.githubusercontent.com/124937355/233206747-091196e4-cd5f-4282-93bd-bbd59b204edf.png)

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos más algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos más algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura,

Muchas gracias por todos los aportes. Hemos hecho una nueva revisión, y hemos notado lo siguiente:
- Las imágenes pueden ser agregadas nuevamente.
- La etapa Multimedia/Conclusion pasa ahora correctamente a "Sources/Comments" al apretar "Save and next".
- La etapa de Institutional Review ya no aparece como requisito para los tipos de instituciones que no la requieren.

Sin embargo, hemos notado que han surgido otros errores:
- Este campo de "Sources" con los enlaces ha desaparecido en el PDF que se genera al mandar el submission form: 
![image](https://user-images.githubusercontent.com/124937355/235992521-60fb149e-1bee-4fd5-8186-855075266827.png)
- Por algún motivo, observamos que la opción para poner un comentario como confidencial:
![image](https://user-images.githubusercontent.com/124937355/235993479-5baf763a-a7cc-4e4d-b6cd-87a338e6995c.png)
solo aprece ahora en la página de Technical Assessment:
![image](https://user-images.githubusercontent.com/124937355/235994056-d888d074-5f9e-4876-80e5-86db3f5a7a47.png)
en las páginas de Basic Screening, End Review, Send Best Practice Revision, y See Best Practice - esta opción ha desaparecido. 
- La opción para subir documentos de manera confidencial en "File Submission" ha desaparecido para todas las páginas.

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

Aquí hay algunos comentarios:

- Este campo de "Sources" con los enlaces ha desaparecido en el PDF que se genera al mandar el submission form.
**Hicimos los cambios requeridos**
- Por algún motivo, observamos que la opción para poner un comentario como confidencial solo aprece ahora en la página de Technical Assessment. En las páginas de Basic Screening, End Review, Send Best Practice Revision, y See Best Practice, esta opción ha desaparecido.
**Hicimos algunas pruebas y la función de comentarios confidenciales funcionó correctamente. Cabe mencionar que existe una regla en el sistema que impide que el Submitter envíe comentarios confidenciales. Es decir, si un usuario con el rol Submitter envía una buena práctica, aunque tenga el rol Secretariat o Reviewer, esa función no estará disponible.**
- La opción para subir documentos de manera confidencial en "File Submission" ha desaparecido para todas las páginas.
**Hicimos algunas pruebas y la función de documentos confidenciales funcionó correctamente. Cabe mencionar que existe una regla en el sistema que impide que el Submitter envíe documentos confidenciales. Es decir, si un usuario con el rol Submitter envía una buena práctica, aunque tenga el rol Secretariat o Reviewer, esa función no estará disponible.**
- Los siguientes campos están apareciendo ahora en los PDF de los submission form en los que estos campos condicionados no aplican/no fueron activados.
**Hicimos los cambios requeridos**

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura,

Muchas gracias por dichas actualizaciones y las aclaraciones.

Solo encuentro un último detalle, el campo "Sources" si vuelve a encontrarse en el PDF, pero no está registrando los links de respuesta. 
Por ejemplo este input:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/af7930b0-e702-4903-9096-f507463feaf0)

Lo muestra vacío en el PDF:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/b017e1f3-686b-41ce-b809-57cda8301c85)

Esto tanto para la primera submission enviada como para versiones subsecuentes de acuerdo a las pruebas.

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura,

El campo Sources, así como los demás se encuentran funcionando bien. Todos los cambios pueden pasar a la versión live.

**Comment by wilsonmoura** [comment]
@AugustoBaron creemos que la actualización de la versión live se llevará a cabo la próxima semana.
