### ISSUE TITLE
Alterações no Portal

### ISSUE THREAD

**Issue by isabellaabe** [bireme/ods3-best-practices#75]
Wilson, Boa noite!
Tudo bom?

Como te expliquei, o nome da Iniciativa mudou, em inglês, de Best Practices para Good Practices. Logo, precisaremos alterar todas as palavras "Best" por "Good" no Portal. Você poderia nos apoiar com isso?

As alterações seriam em todos os lugares do Portal: no formulário de submissão; no formulário de Novo Usuário (no título dele); no logo que está tanto na homepage de login quanto dentro do Portal; nos assuntos dos e-mails enviados pela Portal; nos títulos das listas controladas - ou seja em todos os lugares onde a palavra "Best" aparece terá que ser trocada pela palavra "Good".

Precisamos dessas mudanças, já no ambiente de produção, no máximo até o dia 9.

Muito Obrigada!

Isabella

**Comment by wilsonmoura** [comment]
@marcioalvessilva favor gerar uma nova imagem para inserir no logo do site https://admin.bestpractices.teste.bvsalud.org

Nessa nova imagem, trocar apenas a palavra BEST por GOOD e manter os demais elementos.

**Comment by marcioalvessilva** [comment]
Logo em Formato SVG
![logo-footer-en](https://github.com/bireme/ods3-best-practices/assets/48724136/512e5a62-32ac-4236-ac31-8a93d62e2de3)

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados no ambiente de testes. Favor validar e realizar as devidas traduções.

**Comment by isabellaabe** [comment]
Wilson, boa tarde!
Já fizemos a tradução para o espanhol e português.
Pode passar para o ambiente de produção.
Muito obrigada!
Abraços, 
Isabella
