### ISSUE TITLE
Correos automáticos del Basic Screening

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#76]
Estimado @wilsonmoura ,

Hemos detectado que por algún motivo a nivel del Basic Screening, elegir la opción "Approved" o "Revisions required" envían el contenido del correo ID 11, pero con diferente título de email:

Al elegir opción approved:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/55485060-f9d8-4237-86ef-48576dd2a4d6)

Al elegir opción revisions required:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/1221deea-2663-43e6-a369-6021656e7147)

La opción "Rejected" del Basic Screening si envía un correo separado usando el ID 9.

Me parece que el correo ID 10 no está enlazado con ninguna acción por el momento. ¿Sería posible usarlo para separar los correos de `Approved` y `Revisions required` del Basic Screening?

Muchas gracias por tu apoyo.

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org/

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura, he corroborado que el correo ID 10 se está enviando correctamente con la opción revisions required y el 11 con la opción de approved.

El cambio está listo para pasar a la versión live.

Muchas gracias.
