### ISSUE TITLE
Roles no se pasaron correctamente al ambiente de producción

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#77]
Estimado @wilsonmoura,

Hemos detectado que los roles del sistema que se habían cambiado en el ambiente de test:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/aae20709-bd02-4d6d-8933-77a88d60e6f6)

No se actualizaron por algún motivo en la versión pública al realizar la actualización en la semana pasada:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/288829fa-1d1b-49ed-ae1d-6e771e640e66)

Hemos probado eliminar caché y cookies para evitar visualizar versiones viejas por accidente, pero vemos igual. Solicitamos apoyo para realizar este reacondicionamiento.

Muchas gracias por tu tiempo y apoyo.

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos los ajustes requeridos.

**Comment by AugustoBaron** [comment]
@wilsonmoura Estimado, confirmo que los cambios han sido realizados según lo solicitado. Muchas gracias.
