### ISSUE TITLE
Dos cambios de texto

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#78]
Estimado @wilsonmoura ,

Hemos identificado la necesidad de hacer solo dos leves cambios de texto que hemos omitido previamente. 

1. En el Submission Form, en la siguiente pregunta:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/2b3a66d6-f0c9-46e5-b6db-a6534f76e010)
cambiar el texto de 
`*In your opinion, the resources assigned to the accomplishment of this Good Practice (financial, technological and/or manpower) were implement in an efficient way?`

a 

`*In your opinion, the resources assigned to the accomplishment of this Good Practice (financial, technological and/or manpower) were implemented in an efficient way?`

2. En el Reviewer's Evaluation, en este help icon:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/77b2c457-38fe-428d-b07c-b944d8f369c6)

Cambiar el texto 

`Information on the presence of a financial management structure. Information on a budgetary strategy. Evidence regarding budget ability to reach objectives.`

a

`Information regarding resource adjustments. Information that shows that any surplus of resources was a result of strategic decisions to increase efficiency and not mismanagement. Information regarding strategies to augment/ensure efficiency.`

Agradecemos sinceramente vuestro tan recio apoyo en las últimas semanas, ya con la plataforma finalmente lista para su pronto debut.

Atentamente,
Augusto B.

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos los ajustes requeridos.
