### ISSUE TITLE
Propuesta: Plantillas personalizadas para Evaluación

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#79]
Estimado @wilsonmoura ,

La idea detrás de esta propuesta es poder ofrecerles a las entidades participantes más flexibilidad a la hora de estipular como se hará la evaluación y poder hacer cambios nosotros a la plantilla sin ocupar molestarles tanto.

Esta idea se compone de los siguientes elementos.

**Elemento 1: Creación de una nueva lista controlada "Evaluation Templates"**
Esta lista controlada serviría como punto de partida para crear nuevas plantillas de evaluation para el Reviewer Evaluation.
![controllist copy](https://github.com/bireme/ods3-best-practices/assets/124937355/827f9efe-4417-4702-9dc4-7a4077ea05aa)

El botón de `New Template` abriría una form la cual permita crear una nueva plantilla de evaluación personalizada y/o editar una existente. Tendría la opción de agregar más atributos (o quitarlo si se agregan otros) y poder agregar opciones de puntaje como se requiera. No he agregado campos para los help icons que están en el Reviewer Evaluation por el momento (si esto sería posible agregar directamente desde un form como este, sería ideal).
![template form copy](https://github.com/bireme/ods3-best-practices/assets/124937355/055e899d-f5e8-407a-a90f-cc94494716b1)

**Elemento 2: Selección de Template en la página de Technical Assessment**
La sección de Reviewer's Evaluation de la página Technical Assessment asignadas a Reviewers se subdividiría en dos: Core Attribute Evaluation (Que permanecería con el mismo formato actualmente implementado) y Technical Attribute Evaluation. Para la subsección de Technical Attribute Evaluation, se ocuparía seleccionar que template de evaluación ocupan utlizar (esta selección estaría enlazada con la lista controlada Evaluation Templates) y de acuerdo a la selección, se abriría el formato específico.
![templateinevaluationform copy](https://github.com/bireme/ods3-best-practices/assets/124937355/c2a21579-d4af-4363-b71b-a1cb18e82f3e)

**Elemento 3: Puntuaciones**
Actualmente, la forma muestra un solo puntaje promedio. Sin embargo, se propone que el "Average Score" actual, pase a ser llamado "Core Average Score", que la nueva subsección "Technical Attribute Evaluation" genere un "Technical Average Score" y una nueva versión del "Average Score" dé el promedio de ambos scores individuales.
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/cbbd88be-ede9-4360-81f9-90ab97e5e958)

**Elemento 4: Reporte de revisión**
Actualmente cuando un Reviewer envía su evaluación, la Secretaría recibe el siguiente reporte:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/f364c519-6930-4ec6-90ef-6e4f2721d226)

Como tercer elemento, sería verificar que la secretaría reciba adicionalmente un reporte automático del Technical Attribute Evaluation de acuerdo a la plantilla de evaluación que el Reviewer seleccionó.

Espero que esta versión de la explicación pueda ser un poco más integral. Quedamos a la espera de tus consideraciones sobre la factibilidad de esta proyecto y estimados de tiempo de acuerdo a esta nueva información. Estamos a la orden para cualquier pregunta.

Aclaro que por el momento, solo queremos evaluar la factibilidad de esta idea, no solicitar su implementación aún.

¡Saludos!

**Comment by wilsonmoura** [comment]
@AugustoBaron analizamos esta actividad y, para mantener la estructura actual del sistema y la integridad de los datos, tenemos una sugerencia para satisfacer esta necesidad:

1. Crear la lista controlada Evaluation Attributes:

![Captura de tela de 2023-08-21 20-16-06](https://github.com/bireme/ods3-best-practices/assets/3779520/4bf68047-cfc7-40f7-af1f-a14ff9685f39)

2. En la lista controlada Evaluation Attributes se registrarán todos los atributos técnicos para una determinada convocatoria:

![screenshot-ods3 local bvsalud org-2023 08 21-21_55_02](https://github.com/bireme/ods3-best-practices/assets/3779520/713e7c16-d5ce-42fb-9480-85920b5825e5)

3. Después del registro, los atributos técnicos se mostrarán automáticamente al final de los formularios de evaluación para la respectiva convocatoria:

![screenshot-ods3 local bvsalud org-2023 08 21-23_27_02](https://github.com/bireme/ods3-best-practices/assets/3779520/dcb751fc-2132-4b93-aac1-4594512d484b)

4. Después de que los revisores respondan las evaluaciones de esa respectiva convocatoria, los atributos técnicos también se mostrarán automáticamente en el resumen de las evaluaciones disponible en Technical Assessment:

![screenshot-ods3 local bvsalud org-2023 08 21-22_32_01](https://github.com/bireme/ods3-best-practices/assets/3779520/3108bd5b-05b5-40bb-8529-3c69d33daf92)

5. Y también en el archivo PDF con el resumen de las evaluaciones:

![screenshot-ods3 local bvsalud org-2023 08 21-22_33_19](https://github.com/bireme/ods3-best-practices/assets/3779520/75f5e5e9-a93a-4eb2-a9f1-068d6f9e62f4)

Si lo desea, podemos hacer que una versión de esta sugerencia esté disponible en el ambiente de prueba. Estamos a la espera de sus comentarios.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Muchas gracias por la retroalimentación. Comprendo bien la idea de mantener dos sub-sistemas separados (Evaluation Attributes/Technical Attributes) para facilitar la gestión de los datos.

Tengo unas dudas al respecto de la lista controlada:

- En esta lista por lo que entiendo se seleccionaría a que convocatoria está ligada el "Atributo Técnico" y al seleccionar una convocatoria en el submission form y enviar la bp, el sistema agregaría automáticamente solo los atributos técnicos relevantes a esa convocatoria en la página de technical assessment sin necesidad de inputs adicionales por parte del revisor. ¿Es correcto?

- Una nueva entrada en la lista controlada de atributos técnicos, ¿Permitiría agregar solo un atributo a evaluar por entrada? ¿O todos los atributos de una sola convocatoria serían agregados en una sola entrada? 

- ¿Sería posible ver como se mira la interface de "New Attribute"?

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Gracias por la información adicional. La propuesta se acopla a las necesidades de la inicitativa, además que reducir la necesidad de input por parte de los usuarios es algo beneficioso.

Solo me queda una pregunta, ¿Es posible agregar campos que permitan asimismo automatizar la creación de help icons para las opciones de puntuación? ¿O en su defecto tal vez algún tipo de pop-up text cuando se pase el cursor por la opción de puntuación?

Muchas gracias.

**Comment by wilsonmoura** [comment]
@AugustoBaron el entorno de prueba se ha actualizado y ahora está disponible para validación.

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Gracias por los cambios. Ya no hay problemas con el límite de caracteres y el estilo del texto es visualizado correctamente.

Corroboraré con Eliane esta actualización mañana para el visto bueno del paso al ambiente de producción y confirmo.

Saludos.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Se realizado una revisión de los cambios con las autoridades y esta actualización se encuentra aprobada para pasar al ambiente de producción.

Muchas gracias por tu esfuerzo.

Saludos,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron el ambiente de producción se encontra actualizado.
