### ISSUE TITLE
Propuesta: Implementación de nuevo step para Atributos Técnicos en el formulario de registro

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#80]
Estimado @wilsonmoura ,

Muchas gracias por la provechosa discusión. Dándo seguimiento a la idea de implementar un nuevo step que podríamos llamar "Call Specific Information" en el formulario de registro dirigido a los atributos técnicos, propongo dos tipos de escenarios de como podría ser implementado para tu consideración.

**Escenario 1:** 
El nuevo step "Call Specific Information" se abriría automáticamente bajo la condición de seleccionar un Call específico en el Step 1 "Basic Information":
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/5b20eb3e-2509-43c3-b72b-19916321bde8)

Seleccionar una opción de Call condicionaría la aparición de este nuevo step y abriría un formato de template específico en el Step "Call Specific Information".
Una idea de como podría lograrse esto sería creando una nueva lista controlada "Call Information Templates" en dónde podamos agregar las preguntas a mostrar y poder atribuir el template a una opción de Call (enlazada con la lista controlada Call for Good Practices):
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/c35382b7-4dfe-4b50-b78b-2d1c1751e9e2)

Las opciones de New Template podrían funcionar de la siguiente manera:
 ![template form2](https://github.com/bireme/ods3-best-practices/assets/124937355/1ba265be-5b09-4452-a25d-8b1a8d6caac7)

- Name of the Template: Nombre solo para identificar el template, esta información sería solo para el menú de la lista controlada y no publicada en otra parte.
- Se daría la opción de agregar un título y un subtítulo a cada pregunta, todas estas preguntas automaticamente generarían un text box debajo de la pregunta. 
- El botón New Question permitiría agregar nuevas preguntas en la cantidad que sea necesario.
- Al abrir una segunda pregunta, la opción de borrarla debería ser visible también.
![template form2 1](https://github.com/bireme/ods3-best-practices/assets/124937355/8676f891-deeb-49f6-864c-78f34bd9beab)
- La opción "Link Template to the following Call for Good Practices" mostraría las opciones de la lista controlada "Call for Good Practices" y permitiría enlazar el template con una opción de esa lista controlada para permitir al sistema identificar cual de los template mostrar en el tab "Call Specific Information" del Submission Form.

**Escenario 2:**
En el nuevo step de "Call Specific Information" del Submission form, si no es posible hacerlo automático, solicitar al usuario seleccionar el template correcto. La apariciónde este step, ya que no estaría enlazada a un call específico, podría condicionarse su aparición al solo seleccionar `Yes` en la pregunta `Is this Good Practice being submitted in response to a call for proposals?` en Basic Information. 

Al abrir la página, el usuario deberá seleccionar el template específico a ser utilizado:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/d82a2a8d-90da-4568-8d6f-8bf12c2eb7c6)

Estas opciones estarían siendo agregadas de acuerdo a una lista controlada parecida a la sugerida anteriormente:
![image](https://github.com/bireme/ods3-best-practices/assets/124937355/bcb73579-8fec-4bcf-84bb-09246250574d)

- Name of the Template: Este nombre sería el que aparecería como opción en el breakdown menu "Please confirm your Call for Good Practices:" del nuevo step.
- Se daría la opción de agregar un título y un subtítulo a cada pregunta, todas estas preguntas automaticamente generarían un text box debajo de la pregunta. 
- El botón New Question permitiría agregar nuevas preguntas en la cantidad que sea necesario.
- Al abrir una segunda pregunta, la opción de borrarla debería ser visible también.
 

Quedo pendiente a tus comentarios y consideraciones para evaluar cual sería la mejor manera de implementar esta idea.

Atentamente,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron analizamos esta actividad y, para mantener la estructura actual del sistema y la integridad de los datos, tenemos una sugerencia para satisfacer esta necesidad:

1. Crear la lista controlada Technical Attributes:

![Captura de tela de 2023-08-20 20-16-06](https://github.com/bireme/ods3-best-practices/assets/3779520/8dc0e478-e117-4a68-b31d-4b5467cb5ce3)

2. En la lista controlada Technical Attributes se registrarán todos los atributos técnicos para el formulario de registro relacionado con la respectiva convocatoria:

![screenshot-ods3 local bvsalud org-2023 08 22-01_17_15](https://github.com/bireme/ods3-best-practices/assets/3779520/227e01bc-ddbd-4fbc-b1ec-2056152615c7)

3. Después del registro, los atributos técnicos se mostrarán automáticamente en la pestaña Call Specific Information:

![screenshot-ods3 local bvsalud org-2023 08 22-03_15_55](https://github.com/bireme/ods3-best-practices/assets/3779520/9912333d-f28f-4d78-9a26-c5ede59ad47f)

4. Y también en el archivo PDF con el resumen del formulario de registro:

![screenshot-ods3 local bvsalud org-2023 08 22-03_21_25](https://github.com/bireme/ods3-best-practices/assets/3779520/1e6d2b7d-6378-43ba-8ac7-d172735f68e4)

Si lo desea, podemos hacer que una versión de esta sugerencia esté disponible en el ambiente de prueba para que pueda acceder. Estamos a la espera de sus comentarios.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Muchas gracias por la retroalimentación. Comprendo bien la idea de mantener dos sub-sistemas separados (Evaluation Attributes/Technical Attributes) para facilitar la gestión de los datos.

Tengo unas dudas:

- ¿El tab de Call Specific Information solo aparecería si el sistema detecta al menos un campo asociado a la convocatoria seleccionada? ¿O estaría mostrando una página en blanco solo con el botón de "Save and next"? 

- ¿Sería posible ver como se mira la interface de "New Attribute"?

**Comment by wilsonmoura** [comment]
@AugustoBaron aquí hay algunos comentarios:

- ¿El tab de Call Specific Information solo aparecería si el sistema detecta al menos un campo asociado a la convocatoria seleccionada? ¿O estaría mostrando una página en blanco solo con el botón de "Save and next"?
  - **Exacto. El tab de Call Specific Information solo aparece si el sistema detecta al menos un campo asociado a la convocatoria seleccionada.**

- ¿Sería posible ver como se mira la interface de "New Attribute"?

![screenshot-ods3 local bvsalud org-2023 08 22-13_38_40](https://github.com/bireme/ods3-best-practices/assets/3779520/76996162-fdfd-40ad-87d5-839941e28dbd)

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura,

Muchas gracias por la información adicional, la propuesta se acopla a las necesidades de la inicitativa. 

Solo una sugerencia, a fin de reducir posibles confusiones, sería posible nombrar esta sección en el menu de admin como Technical Attributes (Submitter) y la otra página de admin para agregar los elementos de evaluación como Technical Attributes (Reviewer)?

Por lo demás me parece que podría pasar a la etapa de pruebas al estar listo.

Muchas gracias, quedo pendiente a cualquier comentario.

Saludos,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron El entorno de prueba se ha actualizado y ahora está disponible para validación.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Muchas gracias por el gran esfuerzo. 

Haciendo pruebas que notado que al agregar un New Attribute en Technical Attribute (Submitter), parece que existe un límite de caracteres a partir del cual si se supera y se le presiona Save, la página hace un crash:
![SmartSelect_20230905_104256_Chrome](https://github.com/bireme/ods3-best-practices/assets/124937355/369db398-8399-4872-a15e-d5dccd00964b)

Probé con el siguiente texto: "To the Pan American Health Organization, Good Practices (GPs) are defined as the initiatives, interventions, solutions, methodologies, or procedures undertaken during the implementation of activities and projects at regional, sub-regional, and local levels, which have yielded results that could be adapted and/or replicated in different contexts and by different countries and territories or organizations."

¿Es posible remover este límite? ¿O si es necesario mantenerlo, podríamos especificar dentro de la ventana de New Attribute cual es el límite de palabras a no sobrepasar?

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Muchas gracias por el ajuste. El problema del límite ha sido arreglado.

Haciendo más pruebas, he identificado algunas cosas adicionales a comentar.

- Los campos del Call Specific Information tab no aparecen registrados en el submission form PDF al enviar la BP.

- Me parece que el homepage del Portal de testeo (https://bestpractices.teste.bvsalud.org/) no está sincronizado con la plataforma de admin, no se están publicando las BPs que 'aprobamos' y por ende no podemos ver el producto final. Quisiéramos comprobar si los campos del tab Call Specific Information se están publicando en la página principal o no.

Quedo atento a cualquier comentario.

Saludos,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos más algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Muchas gracias. La sección publicada se mira bien.

Sin embargo, la información de los atributos técnicos sigue sin registrarse en el submission form. 

Si es muy dificultoso incluir esta información en el mismo submission form, tal vez se podría enviar como su PDF separado usando uno de los file types que no están siendo utilizados y se renombra este file type a "Technical Attribute Submission Form"?

**Comment by wilsonmoura** [comment]
@AugustoBaron las pruebas sólo funcionarán si envías un nuevo registro. ¿Puedes volver a realizar la prueba siguiendo estas instrucciones?

**Comment by wilsonmoura** [comment]
@AugustoBaron las pruebas sólo funcionarán si envías un nuevo registro. ¿Puedes volver a realizar las pruebas siguiendo esta orientación?

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Por supuesto.

He hecho una prueba el 7 de Sept, un día después del cambio (submission "test2"), y he vuelto a hacer otra prueba para corroborar de nuevo justo ahora (submission "test3").

En ambos ensayos he notado que no se registran los campos del "Call Specific Information" en el Submission PDF.

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos más algunos ajustes. Por favor, haga más una prueba en https://admin.bestpractices.teste.bvsalud.org

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Gracias por los cambios. Los campos son ahora registrados adecuadamente en el submission PDF.

Corroboraré con Eliane esta actualización mañana para el visto bueno del paso al ambiente de producción y confirmo.

Saludos.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Se realizado una revisión de los cambios con las autoridades y se solicita el siguiente cambio:

- Cambiar de nombre el tab en el submission form de "Call Specific Information" a "Specific Questions of a Call for Good Practices".

Realizando este cambio, la actualización se encuentra aprobada para pasar al ambiente de producción.

Muchas gracias por tu esfuerzo.

Saludos,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron el ambiente de producción se encontra actualizado.
