### ISSUE TITLE
Reestablecimiento del francés

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#84]
Estimado @wilsonmoura ,

Espero te encuentres bien. Recientemente hemos actualizado el kit de traducciones para el francés, por lo que queremos solicitarte de por favor reestablecer la opción de francés en el menu de cambio de lenguaje y actualizar las traducciones.

Quedo pendiente de cualquier comentario.

Gracias siempre por tu apoyo.

Saludos.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Muchas gracias por los cambios realizados. 

Después de una nueva revisión hemos identificado la necesidad de actualizar ciertas traducciones. Por lo que agradecemos una nueva actualización del kit en el ambiente de test.

Junto a esto, hemos identificado que es necesario incluir la opción de descarga de las formas en el tab de "Institutional Review" para el francés:

![image](https://github.com/bireme/ods3-best-practices/assets/124937355/6f8cac64-4962-4c6e-bfdd-7ddad05a1df7)

Dejando las opciones como: 
`Download the form here: English, Español, Português, Français.`

- La opción "Français" en el "Information Requested from Non-State Actors for Engagement with PAHO/WHO" incluiría este hipervínculo: https://admin.bestpractices.bvsalud.org/uploads/documents/fensa-fra.pdf
- La opción "Français" en el "Upload the Tobacco / Arms related disclosure statement for Non-State Actors" incluiría este hipervínculo: https://admin.bestpractices.bvsalud.org/uploads/documents/tobaccoarms-fra.pdf

Quedo pendiente de cualquier comentario o sugerencia.

Agradeciéndote plenamente siempre.

Saludos,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos los ajustes requeridos.
