### ISSUE TITLE
Plantilla de Technical Assessment revierte a versión original en submissions sin Call for GP asignado 

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#85]
Estimado @wilsonmoura ,

Hemos notado que cuando una submission de buena práctica no tiene asignada un Call for Good Practices la página del Technical Assessment se revierte a la versión original, con el único problema que el contador del average score deja de funcionar en estos casos:

![image](https://github.com/bireme/ods3-best-practices/assets/124937355/76167573-fb5a-47f3-aa53-f4b91d534ba7)

Es posible reestablecer esta función? O si es más sencillo, dejar la plantilla actualizada con los Technical Assessments siempre visible aunque la submission no tenga un Call for GP asignado?

Muchas gracias,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://admin.bestpractices.teste.bvsalud.org

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Al hacer algunas pruebas hemos visto que el contador de puntaje funciona adecuadamente ahora. Consideramos listo para pasar al ambiente de producción.

Muchas gracias por tu apoyo. 

Saludos.

**Comment by wilsonmoura** [comment]
@AugustoBaron el ambiente de producción se encontra actualizado.
