### ISSUE TITLE
Separación de propuestas internas y externas

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/ods3-best-practices#86]
Estimado equipo,

Saludos y feliz año nuevo.

En seguimiento a las discusiones tomadas en diciembre, la oficina del director nos ha solicitado incluir una nueva funcionalidad para el Portal de Buenas Prácticas.

El objetivo de esta funcionalidad es que el Portal además de tener buenas prácticas públicas como lo es ahora, tenga la opción de publicar buenas prácticas internas a la OPS que sean solo visibles a las personas con el permiso específico. 

Asimismo, que estas BPs internas tengan algún tipo de flag/metadato para que en la interfase de búsqueda del Portal (o en otra que se considere más oportuna), poder tener una opción para filtrar las buenas prácticas que sean internas de las demás.

Permanecemos pendientes de su propuesta respecto a como se considera que sería el mejor proceder para poder implementar esta idea. 

Estamos a la orden y agradecemos su tiempo. 

Saludos,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron a continuación se muestran imágenes de nuestra sugerencia para implementar esta nueva funcionalidad. Simplemente haga clic en el icono resaltado para marcarlo como privado o público.

![make-non-private-icon](https://github.com/bireme/ods3-best-practices/assets/3779520/22f914a7-4032-4bcd-9765-951b963e8ed0)
![make-private-icon](https://github.com/bireme/ods3-best-practices/assets/3779520/1806754f-aa9c-4829-8107-09e86a78b746)

El ícono en forma de estrella es solo una sugerencia para mostrar en el botón de esta nueva funcionalidad. Por lo tanto, podemos cambiar si tienes otra sugerencia. Aquí te dejo el enlace con la lista de iconos para que puedas evaluar: https://getbootstrap.com/docs/3.3/components/

Respecto al sitio web público, las normas de acceso para la visualización de buenas prácticas sólo se pueden aplicar a los usuarios registrados, siendo esta la única forma de identificar a los usuarios. Es decir, los usuarios registrados e identificados tendrán pleno acceso para visualizar todas las buenas prácticas que se hayan publicado. De lo contrario, los usuarios sólo tendrán acceso al contenido que no haya sido marcado como privado.

Si está de acuerdo, seguiremos con esta sugerencia de implementación.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Gracias por la sugerencia, me parece una solución elegante, pero antes de proseguir tengo unas dudas:

1. `Es decir, los usuarios registrados e identificados tendrán pleno acceso para visualizar todas las buenas prácticas que se hayan publicado. De lo contrario, los usuarios sólo tendrán acceso al contenido que no haya sido marcado como privado.`

La manera de 'identificar' los usuarios con este permiso, ¿Sería a través de un nuevo 'rol' de sistema digamos llamado 'PAHO'? ¿O cómo otorgaríamos el permiso para visualizar BPs privadas a un usuario?

2. Si entiendo correctamente, al momento de publicar una BP, el `Access level `default sería `Private` - y tendríamos manualmente que pasarlas a `Public`. ¿Es esto correcto? ¿O habría una opción en la página de "End Review" para determinar el access level al momento de publicar?

3. Y en seguimiento a esta pregunta, solo los usuarios con rol de `Secretariat` y/o `Administrator` tendrían acceso a esta función de cambiar el `Access level` , ¿Correcto?

Muchas gracias por su tiempo, y feliz año nuevo tardío.

Saludos.

**Comment by wilsonmoura** [comment]
@AugustoBaron feliz año nuevo tardío!

Aquí hay algunos comentarios:

1. La manera de 'identificar' los usuarios con este permiso, ¿Sería a través de un nuevo 'rol' de usuario digamos llamado 'PAHO'? ¿O cómo otorgaríamos el permiso para visualizar BPs privadas a un usuario?
    - Podemos instalar un complemento para identificar a los usuarios con una tag personalizada (por ejemplo, tag PAHO). O también podemos identificar a los usuarios a través de su correo electrónico de registro en el sitio web público. En otras palabras, los usuarios con la dirección de correo electrónico **@paho.org** tendrían acceso completo para ver todo el contenido del sitio web público. Por favor confirme cuál de los dos métodos sería el más apropiado.

2. Si entiendo correctamente, al momento de publicar una BP, el Access level default sería Private - y tendríamos manualmente que pasarlas a Public. ¿Es esto correcto? ¿O habría una opción en la página de "End Review" para determinar el access level al momento de publicar?
    - En este caso nuestra sugerencia sería publicar el contenido automáticamente con el nivel de acceso como privado, para que luego puedas ajustar esta información de la forma más adecuada.

3. Y en seguimiento a esta pregunta, solo los usuarios con rol de Secretariat y/o Administrator tendrían acceso a esta función de cambiar el Access level , ¿Correcto?
    - Exacto!

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Muchas gracias por las respuestas. 

Quisiera saber Wilson, ¿Cuánto tiempo te tendremos disponible para poder coordinar estas actualizaciones? Para así poder adecuar cualquier cosa que tengamos que hacer de nuestra parte.

Adicionalmente, hemos dado una nueva revisada a la propuesta, y nos gustaría establecer con más claridad el aspecto de cómo vamos a enlazar la plataforma de submission y el homepage del Portal para fines de acceso al usuario. Tenemos una propuesta para ello, pero antes de hacer los mock-ups, nos gustaría saber si sería posible integrar el aspecto de "Single Sign-On" para las cuentas de PAHO - con la idea de que este mecanismo nos ayude a controlar en tiempo real quién puede tener o no acceso al contenido "privado"/institucional.

Saludos

**Comment by wilsonmoura** [comment]
@AugustoBaron existe la posibilidad de habilitar SSO en el sitio web público. Pero necesitaremos utilizar algún plug-in que nos permita incorporar esta función. También necesitaremos apoyo del área técnica de la OPS para configurar y permitir el acceso al AD de la OPS. A continuación se muestra un vídeo que explica cómo implementar el inicio de sesión SSO:

https://www.youtube.com/watch?v=kMJOW8zL6EE

También recomendamos otorgar acceso a una persona del área técnica de la OPS para que pueda crear recursos de acceso en el AD de la OPS y configurar el complemento para iniciar sesión en SSO en el siti público.

**Comment by wilsonmoura** [comment]
@AugustoBaron para evitar retrasos en la entrega de esta actividad, nuestra sugerencia es identificar a los usuarios registrados utilizando como referencia el correo electrónico del usuario, según la lógica expuesta en el comentario anterior.

Si está de acuerdo, vamos adelante con esta sugerencia de implementación.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Gracias por la actualización, estaré discutiéndo este tema hoy con Eliane para poder tener su aprobación y decisión final.

Saludos,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron de acuerdo. Luego esperaremos la decisión y los mockups para avanzar con la implementación.

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Gracias por la respuesta, espero que hoy podamos terminar de clarificar todo.

Con respecto a los mock-ups, estos eran más en relación a ver como podemos asegurarnos de establecer visibilidad para que el usuario sepa acceder y que está logged-in a las BP privadas. 

Nos preocupaba el como el usuario (sea identificado de manera automatica o manual) iba a poder acceder a la base de datos con las BPs privadas y sobre todo darle la seguridad que ese acceso está siendo dado.

Sea que el usuario pueda ingresar desde la homepage del portal con algún indicador de que su cuenta está activa (el ícono de fotografía solo es ilustrativo, no requisito):
![loginportal](https://github.com/bireme/ods3-best-practices/assets/124937355/2d433548-9c56-427a-9cb8-816687cfc89b)
![loginportal2](https://github.com/bireme/ods3-best-practices/assets/124937355/add2fe02-2dec-45ef-bbda-458722548cff)

Y/o siempre solo permitir ingreso a través de la página https://admin.portalbp.bvsalud.org/ , pero dejando alguna opción en el menu superior como "Browse Good Practices" para permitir al usuario navegar a la página principal conservando sus privilegios de acceso.
![browsegp](https://github.com/bireme/ods3-best-practices/assets/124937355/3f242c9b-c5a3-4ba5-875e-f5a9dba71260)
Dejando ya sea siempre algún indicador en la página principal de "Logged in" tal vez solo como texto simple en ese caso.
![loginportal3](https://github.com/bireme/ods3-best-practices/assets/124937355/7d10c5b1-bdf1-41a9-9f24-cbea57b72f94)

Creo que estas podrían ser soluciones suplementarias para asegurar que los usuarios tengan seguridad que tienen el acceso esperado. 

Pendiente de tus comentarios.

Saludos

**Comment by wilsonmoura** [comment]
@AugustoBaron al iniciar sesión, siempre se muestra la barra en la parte superior de la página con información sobre el usuario (ver imagen):

![admin-bar](https://github.com/bireme/ods3-best-practices/assets/3779520/98e56bd1-1cd4-4871-8fff-38434f16b9f5)

Por lo tanto, actualizaremos el ambiente de pruebas para que puedas validar los ajustes solicitados.

**Comment by SJanostiac** [comment]
Etapa finalizada: 

[e-mail resposta Augusto sobre SSD.pdf](https://github.com/bireme/ods3-best-practices/files/14484960/e-mail.resposta.Augusto.sobre.SSD.pdf)

**Comment by wilsonmoura** [comment]
@isabellaabe os ajustes foram realizados conforme solicitados. Favor validar no ambiente de testes:

https://bestpractices.teste.bvsalud.org/

**Comment by isabellaabe** [comment]
Boa tarde @wilsonmoura !

Para mim, no ambiente de teste, aparece a mesma estrutura. Ou seja, nenhum ajuste...
Poderia confirmar para mim se o ajuste segue visível no ambiente de teste?
Obrigada!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe no ambiente de testes do [site administrativo](https://admin.bestpractices.teste.bvsalud.org), agora é possível definir se um conteúdo será privado o público após a sua aprovação (necessário perfil **Secretariat**). Já no [site público](https://bestpractices.teste.bvsalud.org), usuários logados e que foram cadastrados com e-mail que pertence ao domínio **@paho.org** vão ter acesso aos conteúdos privados. Caso contrário, somente os conteúdos públicos vão estar disponíveis para os usuários.
